/**
 * effectivity CMS configuration for this repository's reference Worker.
 * Source of truth for `wrangler.jsonc` and `src/runtime.generated.ts`
 * (both generated by `bun run cms sync`). Defaults keep a fresh checkout
 * working locally; production overlays the secret values at deploy time.
 */
import { defineConfig } from "@effectivity/cli"

export default defineConfig({
  name: "effectivity-cms",
  catalog: {
    // Logical catalog root inside the R2 bucket (was the CMS_ROOT var).
    root: "cms",
  },
  auth: {
    // Public origin for auth cookies/CSRF (was AUTH_URL).
    url: "http://localhost:8787",
    admin: {
      // Provisioned at first boot (was AUTH_ADMIN_EMAIL).
      email: "admin@effectivity.local",
      // Never baked into a bundle: `bun run cms dev` writes it to
      // .dev.vars; `bun run cms deploy` puts it as a wrangler secret.
      password: "admin-seed-password-0123",
    },
    // signing secret (was AUTH_SECRET): the dev default is baked so local
    // runs need no plumbing; production overlays it via a wrangler secret.
    // secret: "<64-hex-random>",
  },
  cloudflare: {
    r2: { bucket: "effectivity-cms" },
    d1: {
      name: "effectivity-auth",
      // Optional: `bun run cms deploy --provision` creates the database and
      // records the real id in cms.state.json, which the generator prefers.
      // id: "6d5f3a2e-0000-4000-8000-000000000000",
    },
  },
})
