/**
 * effectivity configuration for this repository's reference Worker.
 * Source of truth for wrangler.jsonc and src/runtime.generated.ts
 * (both generated by `bun run cms sync`). Defaults keep a fresh checkout
 * working locally; production overlays the secret values at deploy time.
 */
import { defineConfig } from "@effectivity/cli"
import { cloudflarePlugin } from "@effectivity/cloudflare"

export default defineConfig({
  plugins: [
    cloudflarePlugin({
      name: "effectivity-cms",
      r2: { bucket: "effectivity-cms" },
      d1: { name: "effectivity-auth" },
      auth: {
        url: "http://localhost:8787",
        admin: {
          email: "admin@effectivity.local",
          // Never baked into a bundle: `bun run cms dev` writes it to
          // .dev.vars; production overlays it at deploy time.
          password: "admin-seed-password-0123",
        },
      },
      catalog: { root: "cms" },
    }),
  ],
})