/**
 * Generated by @effectivity/cli from cms.config.ts — do not hand-edit.
 * Regenerate with `effectivity sync` (this repo: `bun run cms sync`).
 *
 * Runtime settings born from the config object instead of environment
 * variables. Secrets are NOT baked: the admin password lives in
 * .dev.vars (dev) / wrangler secrets (deploy); production may overlay any
 * baked value via AUTH_URL / AUTH_SECRET / AUTH_ADMIN_EMAIL vars.
 */
export const settings = {
  catalog: {
    root: "cms",
  },
  auth: {
    url: "http://localhost:8787",
    secret: "dev-secret-0123456789abcdef0123456789abcdef",
    admin: {
      email: "admin@effectivity.local",
    },
  },
} as const
