/**
 * Derive the deployable surface from a resolved config: the bindings-only
 * `wrangler.jsonc` and the runtime settings module baked into the worker
 * bundle. Secrets never appear here — `auth.admin.password` goes to
 * `.dev.vars`/wrangler secrets, and production overlays the baked dev secret
 * through `AUTH_SECRET`/`AUTH_URL`/`AUTH_ADMIN_*` environment variables.
 */
import { mkdir, readFile, writeFile } from "node:fs/promises"
import { dirname, join } from "node:path"
import type { ResolvedCmsConfig } from "./config.ts"

export const runtimeModulePath = (dir: string): string => join(dir, "src", "runtime.generated.ts")
export const wranglerConfigPath = (dir: string): string => join(dir, "wrangler.jsonc")
export const statePath = (dir: string): string => join(dir, "cms.state.json")
export const devVarsPath = (dir: string): string => join(dir, ".dev.vars")

/**
 * Deploy-time state that must survive regeneration: e.g. the D1 database id
 * returned by `wrangler d1 create`, which the config author should not need
 * to paste back into cms.config.ts by hand.
 */
export interface CmsState {
  readonly d1Id?: string
}

export const readState = async (dir: string): Promise<CmsState> => {
  try {
    return JSON.parse(await readFile(statePath(dir), "utf8")) as CmsState
  } catch {
    return {}
  }
}

export const writeState = async (dir: string, state: CmsState): Promise<void> => {
  await writeFile(statePath(dir), `${JSON.stringify(state, null, 2)}\n`)
}

/** The d1 id to emit: real id from deploy state, else config, else placeholder. */
export const d1IdOf = (config: ResolvedCmsConfig, state: CmsState): string =>
  state.d1Id ?? config.cloudflare.d1.id ?? "00000000-0000-0000-0000-000000000000"

/** The generated runtime settings module (non-secret fields only). */
export const generateRuntimeModule = (config: ResolvedCmsConfig): string => {
  const settings = {
    catalog: { root: config.catalog.root },
    auth: {
      url: config.auth.url,
      // Dev signing secret baked for local runs; production overlays it via a
      // `wrangler secret put AUTH_SECRET` (the deployed worker env wins).
      secret: config.auth.secret,
      admin: { email: config.auth.admin.email },
    },
  }
  return (
    [
      "/**",
      " * Generated by @effectivity/cli from cms.config.ts — do not hand-edit.",
      " * Regenerate with `effectivity sync` (this repo: `bun run cms sync`).",
      " *",
      " * Runtime settings born from the config object instead of environment",
      " * variables. Secrets are NOT baked: the admin password lives in",
      " * .dev.vars (dev) / wrangler secrets (deploy); production may overlay any",
      " * baked value via AUTH_URL / AUTH_SECRET / AUTH_ADMIN_EMAIL vars.",
      " */",
      `export const settings = ${JSON.stringify(settings, null, 2)} as const`,
    ].join("\n") + "\n"
  )
}

/** Bindings-only Workers config; every runtime setting lives in the settings module. */
export const generateWranglerConfig = (config: ResolvedCmsConfig, d1Id: string): string =>
  [
    "// Generated by @effectivity/cli from cms.config.ts (source of truth) —",
    "// hand-edits are overwritten. Bindings only: runtime settings live in",
    "// src/runtime.generated.ts; secrets go to .dev.vars (dev) / wrangler",
    "// secret put (prod), never into vars.",
    "{",
    `  "$schema": "node_modules/wrangler/config-schema.json",`,
    `  "name": ${JSON.stringify(config.name)},`,
    '  "main": "src/index.ts",',
    '  "compatibility_date": "2026-08-15",',
    '  "compatibility_flags": ["nodejs_compat"],',
    '  "r2_buckets": [',
    "    {",
    '      "binding": "BUCKET",',
    `      "bucket_name": ${JSON.stringify(config.cloudflare.r2.bucket)}`,
    "    }",
    "  ],",
    '  "d1_databases": [',
    "    {",
    '      "binding": "DB",',
    `      "database_name": ${JSON.stringify(config.cloudflare.d1.name)},`,
    `      "database_id": ${JSON.stringify(d1Id)}`,
    "    }",
    "  ],",
    '  "observability": {',
    '    "enabled": true,',
    '    "traces": { "enabled": true }',
    "  }",
    "}",
    "",
  ].join("\n")

/** Regenerate both artifacts for a config directory. */
export const sync = async (dir: string, config: ResolvedCmsConfig): Promise<void> => {
  const state = await readState(dir)
  const d1Id = d1IdOf(config, state)
  await mkdir(dirname(runtimeModulePath(dir)), { recursive: true })
  await writeFile(runtimeModulePath(dir), generateRuntimeModule(config))
  await writeFile(wranglerConfigPath(dir), generateWranglerConfig(config, d1Id))
}

/**
 * Merge the CLI's dev-only secret values into `.dev.vars`, preserving any
 * hand-written keys. Returns the updated text.
 */
export const mergeDevVars = async (
  dir: string,
  values: Readonly<Record<string, string>>,
): Promise<string> => {
  let lines: string
  try {
    lines = await readFile(devVarsPath(dir), "utf8")
  } catch {
    lines = ""
  }
  const entries = new Map(
    lines
      .split(/\r?\n/)
      .map((line) => line.trim())
      .filter((line) => line !== "" && !line.startsWith("#") && line.includes("="))
      .map((line) => {
        const [key, ...rest] = line.split("=")
        return [key!, rest.join("=")]
      }),
  )
  for (const [key, value] of Object.entries(values)) {
    entries.set(key, value)
  }
  const body = [...entries.entries()].map(([key, value]) => `${key}=${value}`).join("\n")
  const content = body === "" ? "" : `${body}\n`
  await writeFile(devVarsPath(dir), content)
  return content
}
